import { makeStyles } from "@mui/styles";
import { themeShadows } from "../../../theme/shadows";
const useStyles = makeStyles((theme) => ({
  main: {
    margin: "50px auto",
    width: "90%",
    height: "500px",
    color: theme.palette.secondary.contrastText,
  },
  sub_container: {
    // maxWidth: "424.84px",
    width: "90%",
    height: "40vh",
    // height: "auto",
    boxShadow: themeShadows().z12,
  },
  detail: {
    maxWidth: "90%",
    height: "auto",
    marginTop: "20vh",
    position: "absolute",
    background: "#fff",
    margin: "0 auto",
    color: "#333",
    boxShadow: themeShadows().primary,
    borderColor: theme.palette.primary.main,
    border: "1px solid",
    borderRadius: "16px",
    position: "relative",
    top: "-16%",
  },
  img: {
    // maxWidth: "100%",
    // width: "380px",
    width: "100%",
    // height: "460px",
    // objectFit: "cover",
    borderRadius: "16px",
  },
  titles: {
    fontFamily: "Poppins",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: "24px",
    lineHeight: "124.5%",
    color: "#5E6282",
  },
  Carousel: {
    position: "absolute",
  },
  Container: {
    minHeight: "100vh",
    width: "100%",
    // backgroundImage: `url(${background})`,
    position: "static",
    backgroundSize: "fixed",
  },
  AddTask: {
    minHeight: "30%",
    position: "sticky",
    top: 0,
    zIndex: 1,
    // backgroundImage: `url(${header})`,
    // backgroundSize: "cover",
  },
  ModalContainer: {
    // backgroundImage: `url(${modalBackground})`,
    backgroundSize: "cover",
    borderRadius: 12,
    marginTop: "10vh",
    opacity: "0.9",
    minWidth: "70vw",
    maxWidth: "80vw",
    minHeight: "70vh",
    maxHeight: "80vh",
    margin: "auto",
  },
  Title: {
    textAlign: "center",
    color: "#000050",
    fontSize: "20px !important",
    fontWeight: "900 !important",
    textDecorationLine: "underline",
  },
  Input: {
    width: "40% !important",
    marginLeft: "30% !important",
    marginRight: "30% !important",
    marginTop: "7px !important",
  },
  TasksContainer: {
    minWidth: "80%",
    marginInline: "10%",
  },
  Accordions: {
    border: "1px solid #09A391",
    marginInline: "12px !important",
    borderRadius: "15px !important",
  },
  TaskTitle: {
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      marginInline: "auto",
    },
    fontSize: "16px",
    fontWeight: "600 !important",
    color: "navy",
    textDecorationLine: "underline",
  },
  DateStyle: {
    paddingLeft: "12%",
    minWidth: "20%",
  },
  TimeStyle: {
    paddingLeft: "6%",
    minWidth: "20%",
  },
  EditIconStyle: {
    paddingLeft: "4%",
    color: "black",
  },
  DeleteIconStyle: {
    paddingLeft: "11%",
    paddingTop: "5px",
  },
}));
export default useStyles;
